export let types = [
    {
        "long":"Acid",
        "short":"A",
        "target":"EAC"
    },
    {
        "long":"Cold",
        "short":"C",
        "target":"EAC"
    },
    {
        "long":"Electricity",
        "short":"E",
        "target":"EAC"
    },
    {
        "long":"Fire",
        "short":"F",
        "target":"EAC"
    },
    {
        "long":"Sonic",
        "short":"So",
        "target":"EAC"
    },
    {
        "long":"Bludgeoning",
        "short":"B",
        "target":"KAC"
    },
    {
        "long":"Piercing",
        "short":"P",
        "target":"KAC"
    },
    {
        "long":"Slashing",
        "short":"S",
        "target":"KAC"
    }
];